import Head from "next/head";
import { useState } from "react";

import { trpc } from "../utils/trpc";

const Home = () => {
  const { data, isLoading, refetch } = trpc.invoice.getAll.useQuery();
  const statusMutation = trpc.invoice.approve.useMutation()

  const approve = (event) => {
    let id = event.target.value
    statusMutation.mutate({id}, {
      onSettled() {
        refetch()
      },
    })
  }

  if (isLoading)
    return (
      <>Loading Data...</>
    )

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <table className="table-fixed w-11/12 border-solid border-l border-t border-b border-r mt-4">
          <thead className="table-header-group">
            <tr>
              <th></th>
              <th>Invoice Number</th>
              <th>Vendor Name</th>
              <th className="w-60">Vendor Address</th>
              <th>Invoice Total</th>
              <th>Invoice Date</th>
              <th>Due Date</th>
            </tr>
          </thead>
          <tbody className="text-center">
            {
              data?.map(invoice => (
                <tr key={invoice.id}>
                  <td><button className="bg-blue-700 text-white mr-2 ml-2 p-2 rounded-sm" value={invoice.id} onClick={approve}>Approve</button></td>
                  <td>{invoice.invoice_number}</td>
                  <td>{invoice.vendor_name}</td>
                  <td>{invoice.remittance_address}</td>
                  <td>{invoice.total}</td>
                  <td>{invoice.invoice_date}</td>
                  <td>{invoice.due_date}</td>
                </tr>
              ))
            }
          </tbody>
        </table>
      </main>
    </>
  );
};

export default Home;
